Made deployer and runner SA's not hard coded. Fixes namespacing bug.

diff --git a/kubectl-createns b/kubectl-createns
--- a/kubectl-createns
+++ b/kubectl-createns
@@ -24,64 +24,15 @@
 # <https://www.gnu.org/licenses/>.                                        #
 ###########################################################################
 
-psp_name="ourrestrictedpsp"
-
-psp_yaml="
-apiVersion: policy/v1beta1
-kind: PodSecurityPolicy
-metadata:
-  name: ${psp_name}
-  annotations:
-    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
-    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
-    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
-    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
-spec:
-  privileged: false
-  # Required to prevent escalations to root.
-  allowPrivilegeEscalation: false
-  # This is redundant with non-root + disallow privilege escalation,
-  # but we can provide it for defense in depth.
-  requiredDropCapabilities:
-    - ALL
-  # Allow core volume types.
-  volumes:
-    - 'configMap'
-    - 'emptyDir'
-    - 'projected'
-    - 'secret'
-    - 'downwardAPI'
-    # Assume that persistentVolumes set up by the cluster admin are safe to use.
-    - 'persistentVolumeClaim'
-  hostNetwork: false
-  hostIPC: false
-  hostPID: false
-  runAsUser:
-    # Require the container to run without root privileges.
-    rule: 'MustRunAsNonRoot'
-  seLinux:
-    # This policy assumes the nodes are using AppArmor rather than SELinux.
-    rule: 'RunAsAny'
-  supplementalGroups:
-    rule: 'MustRunAs'
-    ranges:
-      # Forbid adding the root group.
-      - min: 1
-        max: 4294967294
-  fsGroup:
-    rule: 'MustRunAs'
-    ranges:
-      # Forbid adding the root group.
-      - min: 1
-        max: 4294967294
-  readOnlyRootFilesystem: false
-"
+psp_name="restricted"
+deployer_sa_name="deployer"
+runner_sa_name="runner"
 
 runner_role_yaml="
 apiVersion: rbac.authorization.k8s.io/v1
 kind: Role
 metadata:
-  name: runner-role
+  name: ${runner_sa_name}-role
 rules:
 - apiGroups: ['policy']
   resources: ['podsecuritypolicies']
@@ -94,21 +45,21 @@ runner_rolebinding_yaml="
 apiVersion: rbac.authorization.k8s.io/v1
 kind: RoleBinding
 metadata:
-  name: runner-rolebinding
+  name: ${runner_sa_name}-rolebinding
 roleRef:
   kind: Role
-  name: runner-role
+  name: ${runner_sa_name}-role
   apiGroup: rbac.authorization.k8s.io
 subjects:
 - kind: ServiceAccount
-  name: runner
+  name: ${runner_sa_name}
 "
 
 deployer_role_yaml="
 apiVersion: rbac.authorization.k8s.io/v1
 kind: Role
 metadata:
-  name: deployer-role
+  name: ${deployer_sa_name}-role
 rules:
 - apiGroups: ['policy']
   resources: ['podsecuritypolicies']
@@ -119,7 +70,7 @@ rules:
   resources: ['serviceaccounts']
   verbs:     ['use']
   resourceNames:
-  - runner
+  - ${runner_sa_name}
 - apiGroups: ['']
   resources: ['pods']
   verbs:     ['get','list','delete','watch']
@@ -135,14 +86,14 @@ deployer_rolebinding_yaml="
 apiVersion: rbac.authorization.k8s.io/v1
 kind: RoleBinding
 metadata:
-  name: deployer-rolebinding
+  name: ${deployer_sa_name}-rolebinding
 roleRef:
   kind: Role
-  name: deployer-role
+  name: ${deployer_sa_name}-role
   apiGroup: rbac.authorization.k8s.io
 subjects:
 - kind: ServiceAccount
-  name: deployer
+  name: ${deployer_sa_name}
 "
 
 set -euo pipefail
@@ -204,6 +155,8 @@ elif [ "${fixup}" -eq "0" ]; then
 	die "Cannot apply artifacts to current namespace with \"--fixup\"."
 fi
 
+kubectl get podsecuritypolicy "${psp_name}"  > /dev/null 2>&1 || die "PodSecurityPolicy \"${psp_name}\" does not exist. Please create it before running this tool."
+
 trap cleanup EXIT
 
 if [ "${exists}" -eq "0" ]; then
@@ -212,19 +165,15 @@ if [ "${exists}" -eq "0" ]; then
 	nsc="-n ${ns}"
 fi
 
-if [ -z "$(kubectl get sa deployer ${nsc} --no-headers 2>/dev/null || true)" ]; then
-	kubectl create serviceaccount deployer ${nsc} || die "Could not create deployer service account."
-fi
-
-if [ -z "$(kubectl get sa runner ${nsc} --no-headers 2>/dev/null || true)" ]; then
-	kubectl create serviceaccount runner ${nsc} || err "Could not create runner service account."
-fi
-
-for sa in default deployer runner; do
-	kubectl patch serviceaccount "${sa}" -p '{"automountServiceAccountToken": false}'
+for sa in ${deployer_sa_name} ${runner_sa_name}; do
+	if [ -z "$(kubectl get sa "${sa}" ${nsc} --no-headers 2>/dev/null || true)" ]; then
+		kubectl create serviceaccount "${sa}" ${nsc} || die "Could not create \"${sa}\" service account."
+	fi
 done
 
-echo "${psp_yaml}" | kubectl apply -f-
+for sa in default ${deployer_sa_name} ${runner_sa_name}; do
+	kubectl patch serviceaccount "${sa}" ${nsc} -p '{"automountServiceAccountToken": false}'
+done
 
 echo "${runner_role_yaml}" | kubectl apply -f- ${nsc}
 echo "${runner_rolebinding_yaml}" | kubectl apply -f- ${nsc}
